apiVersion: "resiliencebench.io/v1"
kind: ResilientService
metadata:
  name: productpage
  annotations:
    resiliencebench.io/library: resilience4j
    resiliencebench.io/platform: resilience4j
    resiliencebench.io/create-istio-virtualservice: true
spec:
  selector:
    matchLabels:
      app: productpage
---
apiVersion: "resiliencebench.io/v1"
kind: ResilientService
metadata:
  name: details
spec:
  selector:
    matchLabels:
      app: details
---
apiVersion: "resiliencebench.io/v1"
kind: ResilientService
metadata:
  name: ratings
spec:
  selector:
    matchLabels:
      app: ratings
---
apiVersion: "resiliencebench.io/v1"
kind: ResilientService
metadata:
  name: ratings-v1
spec:
  selector:
    matchLabels:
      app: ratings-v1
---
apiVersion: "resiliencebench.io/v1"
kind: ResilientService
metadata:
  name: reviews
spec:
  selector:
    matchLabels:
      app: reviews
---
apiVersion: "resiliencebench.io/v1"
kind: ResilientService
metadata:
  name: reviews-v1
spec:
  selector:
    matchLabels:
      app: reviews-v1
---
apiVersion: "resiliencebench.io/v1"
kind: ResilientService
metadata:
  name: reviews-v2
spec:
  selector:
    matchLabels:
      app: reviews-v2
---
apiVersion: "resiliencebench.io/v1"
kind: ResilientService
metadata:
  name: reviews-v3
spec:
  selector:
    matchLabels:
      app: reviews-v3

---
