apiVersion: "resiliencebench.io/v1beta1"
kind: Workload
metadata:
  name: stress-test
spec:
  users: [10, 20, 30]
  duration: 100 #seconds
  targetUrl: "http://"
  script:
    configMap:
      name: bookinfo-stress-test
      file: bookinfo-stress-test.js

---

apiVersion: "resiliencebench.io/v1beta1"
kind: ResilientService
metadata:
  name: api-gateway
  annotations:
    resiliencebench.io/library: resilience4j
spec:
  selector:
    matchLabels:
      com.petclinic.service: api-gateway
---
apiVersion: "resiliencebench.io/v1beta1"
kind: ResilientService
metadata:
  name: vets-service
  annotations:
    resiliencebench.io/library: resilience4j
spec:
  selector:
    matchLabels:
      com.petclinic.service: vets-service
---
apiVersion: "resiliencebench.io/v1beta1"
kind: ResilientService
metadata:
  name: visits-service
  annotations:
    resiliencebench.io/library: resilience4j
spec:
  selector:
    matchLabels:
      com.petclinic.service: visits-service
---
apiVersion: "resiliencebench.io/v1beta1"
kind: ResilientService
metadata:
  name: customers-service
  annotations:
    resiliencebench.io/library: resilience4j
spec:
  selector:
    matchLabels:
      com.petclinic.service: customers-service

---

apiVersion: resiliencebench.io/v1beta1
kind: Benchmark
metadata:
  name: example-benchmark
  namespace: default
spec:
  rounds: 5
  workload: stress-test
  connections:
    - name: connection-1
      source:
        service: api-gateway
        patternConfig:
          - name: patternKey1
            value: value1
          - name: patternKey2
            value: value2
      target:
        service: vets-service
        fault:
          percentage: [10, 20]
          delay:
            duration: 100
    - name: connection-2
      source:
        service: api-gateway
        patternConfig:
          - name: patternKey3
            value: value3
          - name: patternKey4
            value: value4
      target:
        service: visits-service
        fault:
          percentage: [10, 20]
          abort:
            httpStatus: 503