cloud:
  aws:
    region:
      static: us-east-1
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}

storage:
  results:
    bucketName: phd-carlos-results
