# .github/workflows/build-test.yml
name: Build and Test Java 17 with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Create Kind Cluster
      uses: helm/kind-action@v1.5.0
    - name: Test with Maven
      run: | 
        kubectl cluster-info --context kind-chart-testing
        mvn -B compile --file pom.xml
        kubectl apply -f ./target/classes/META-INF/fabric8
        kubectl get crd
        mvn -B test --file pom.xml